name: over_the_bike_fit
description: Final stable build
version: 2.1.0+2100

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.1
  fl_chart: ^0.66.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/splash/splash_screen.png
    - assets/icon/app_icon.png

# 아이콘 생성 설정을 더 명확하게 수정
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#000000"
  image: assets/splash/splash_screen.png
